// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package user

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type UserStatus string

const (
	UserStatusActive  UserStatus = "active"
	UserStatusLocked  UserStatus = "locked"
	UserStatusDeleted UserStatus = "deleted"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type User struct {
	// 用户ID
	ID uuid.UUID `json:"id"`
	// 显示名称
	DisplayName string `json:"display_name"`
	// 头像地址
	AvatarUrl pgtype.Text `json:"avatar_url"`
	// 默认语言
	Locale pgtype.Text `json:"locale"`
	// 默认时区
	Timezone pgtype.Text `json:"timezone"`
	// 用户状态
	Status NullUserStatus `json:"status"`
	// 安全版本
	SecurityVersion pgtype.Int8 `json:"security_version"`
	// 锁定时间
	LockedAt pgtype.Timestamptz `json:"locked_at"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// 删除时间
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}
