// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package user

import (
	"context"
)

const getUserList = `-- name: GetUserList :many
SELECT  FROM user
`

type GetUserListRow struct {
}

func (q *Queries) GetUserList(ctx context.Context) ([]GetUserListRow, error) {
	rows, err := q.db.Query(ctx, getUserList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserListRow{}
	for rows.Next() {
		var i GetUserListRow
		if err := rows.Scan(); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
