// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package user

import (
	"context"
)

type Querier interface {
	GetUserList(ctx context.Context) ([]GetUserListRow, error)
}

var _ Querier = (*Queries)(nil)
